import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>aws-lambda-trigger</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>
          Use /api/trigger-webhook to trigger the demo aws lambda function.
          Provide it with a json payload of
        </h1>
        <code>
          n8nWebhookUrl: your aws lambda trigger node webhook url,
          <br />
          forwardBody: Body object you want to forward to n8n
        </code>
      </main>
    </div>
  );
}
